### ISSUE TITLE
Some notifications are shown twice if Telegram is open

### ISSUE THREAD

**Issue by marco-c** [zhukov/webogram#1301]
As noted in #1298, some notifications are shown twice when a Telegram tab is already open.

Probably because of https://github.com/zhukov/webogram/issues/1298#issuecomment-268038228:
> Oh, I've noticed you're using the global scope there.
With service workers, it isn't reliable to use variables from the global scope in event handlers (see https://developer.mozilla.org/it/docs/Web/API/ServiceWorkerGlobalScope or https://jakearchibald.com/2016/service-worker-meeting-notes/).
> (so, lastAliveTime is likely to often evaluate to false here: https://github.com/zhukov/webogram/blob/master/app/js/lib/push_worker.js#L48)

**Comment by kskarthik** [comment]
For me too :/

**Comment by zhukov** [comment]
I might have fixed all the issues in recent commits like this: https://github.com/zhukov/webogram/commit/e9770d2746db7f519174545d66890b0d285af392

Can you try again?

**Comment by marco-c** [comment]
@zhukov, it looks like the Firefox detection is still in the global scope. This means it isn't reliable, `userInvisibleSupported` might evaluate to false here (https://github.com/zhukov/webogram/blob/e9770d2746db7f519174545d66890b0d285af392/app/js/lib/push_worker.js#L33) even on Firefox.

**Comment by marco-c** [comment]
It's still happening unfortunately :(

**Comment by marco-c** [comment]
Reproducing is simple. Open telegram, get a message, see the first notification, don't focus the telegram tab, after a while you'll get the second notification.
Clicking on the second notification will open a new telegram tab.

**Comment by zhukov** [comment]
@marco-c Hm. Can you double check that the app was updated and a new service worker is active?

**Comment by zhukov** [comment]
Because
1. I can't reproduce issue with the steps you provided
2. I think I've fixed the problem with opening new tab (instead of using existing) with the latest release.

**Comment by marco-c** [comment]
I'll test again soon. Have you fixed it on web.telegram.org?

**Comment by zhukov** [comment]
Yes. It was already updated when I've sent this comment: https://github.com/zhukov/webogram/issues/1301#issuecomment-268292715

**Comment by zhukov** [comment]
@marco-c  oh, nevermind. I've been able to reproduce after I've updated Fx to the most recent version. Will look into it.

**Comment by marco-c** [comment]
Has the change been released already? I'm still experiencing the same problem.

**Comment by zhukov** [comment]
@marco-c Nope, just for beta (zhukov.github.io/webogram). Will probably release today to web.telegram.org.

**Comment by zhukov** [comment]
@marco-c the change was released to https://web.telegram.org. Please try again.
